package oving5;

public class Simulator {
	
	//Dog goes woof.
	//Cat goes meow.
	//bird goes tweet.
	//and mouse go squeek.
	//COW GOES
	//MOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO
	//OOOOOOOOOOOOOOOO!
}
